# Generated by Django 5.2.5 on 2025-10-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingslot',
            name='slot_type',
            field=models.CharField(choices=[('two_wheeler', 'Two Wheeler'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('large', 'Large Vehicle'), ('disabled', 'Disabled'), ('vip', 'VIP/Reserved')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('two_wheeler', 'Two Wheeler'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('large', 'Large Vehicle')], max_length=20),
        ),
    ]
