# Generated by Django 5.2.5 on 2025-10-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0005_merge_sedan_suv_to_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingslot',
            name='slot_type',
            field=models.CharField(choices=[('two_wheeler', 'Two Wheeler'), ('car', 'Cars'), ('large', 'Large Vehicle'), ('disabled', 'Disabled'), ('vip', 'VIP/Reserved')], max_length=20),
        ),
    ]
