# Generated by Django 5.1.1 on 2025-11-05 10:02

from django.db import migrations, models


def create_unique_index(apps, schema_editor):
    """Create a unique index for Oracle to prevent duplicate active sessions"""
    if schema_editor.connection.vendor == 'oracle':
        # Oracle doesn't support partial unique constraints directly
        # We use a function-based unique index instead
        with schema_editor.connection.cursor() as cursor:
            # STEP 1: Clean up duplicate active sessions FIRST
            print("🧹 Cleaning duplicate active sessions before creating constraint...")
            
            # Find slots with duplicate active sessions
            cursor.execute("""
                SELECT parking_slot_id, COUNT(*) as session_count
                FROM PARKING_APP_PARKINGSESSION
                WHERE IS_ACTIVE = 1
                GROUP BY parking_slot_id
                HAVING COUNT(*) > 1
            """)
            
            duplicate_slots = cursor.fetchall()
            
            if duplicate_slots:
                print(f"⚠️ Found {len(duplicate_slots)} slot(s) with duplicate active sessions")
                
                for slot_id, count in duplicate_slots:
                    # Get the most recent session for this slot
                    cursor.execute("""
                        SELECT ID FROM (
                            SELECT ID, ENTRY_TIME
                            FROM PARKING_APP_PARKINGSESSION
                            WHERE PARKING_SLOT_ID = :slot_id AND IS_ACTIVE = 1
                            ORDER BY ENTRY_TIME DESC
                        ) WHERE ROWNUM = 1
                    """, {'slot_id': slot_id})
                    
                    keep_session = cursor.fetchone()[0]
                    
                    # Deactivate all other sessions for this slot
                    cursor.execute("""
                        UPDATE PARKING_APP_PARKINGSESSION
                        SET IS_ACTIVE = 0, 
                            STATUS = 'Completed',
                            EXIT_TIME = SYSDATE
                        WHERE PARKING_SLOT_ID = :slot_id 
                          AND IS_ACTIVE = 1 
                          AND ID != :keep_id
                    """, {'slot_id': slot_id, 'keep_id': keep_session})
                    
                    print(f"  ✅ Fixed slot ID {slot_id}: Kept session {keep_session}, deactivated {count-1} older session(s)")
            else:
                print("✅ No duplicate active sessions found")
            
            # STEP 2: Drop index if it exists
            try:
                cursor.execute("""
                    BEGIN
                        EXECUTE IMMEDIATE 'DROP INDEX unique_active_session_idx';
                    EXCEPTION
                        WHEN OTHERS THEN
                            IF SQLCODE != -1418 THEN
                                RAISE;
                            END IF;
                    END;
                """)
            except:
                pass
            
            # STEP 3: Create function-based unique index
            # This creates a unique index on (parking_slot_id, is_active) where is_active=1
            cursor.execute("""
                CREATE UNIQUE INDEX unique_active_session_idx 
                ON PARKING_APP_PARKINGSESSION (
                    CASE WHEN IS_ACTIVE = 1 THEN PARKING_SLOT_ID ELSE NULL END,
                    CASE WHEN IS_ACTIVE = 1 THEN IS_ACTIVE ELSE NULL END
                )
            """)
            print("✅ Created unique index to prevent duplicate active sessions")


def drop_unique_index(apps, schema_editor):
    """Drop the unique index"""
    if schema_editor.connection.vendor == 'oracle':
        with schema_editor.connection.cursor() as cursor:
            try:
                cursor.execute("DROP INDEX unique_active_session_idx")
            except:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0007_parkingslot_status'),
    ]

    operations = [
        migrations.RunPython(create_unique_index, drop_unique_index),
    ]
