# Generated by Django 5.1.1 on 2025-12-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0008_add_unique_active_session_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingsession',
            name='entry_time',
            field=models.DateTimeField(),
        ),
    ]
