# Generated by Django 5.2.5 on 2025-10-07 17:21

import django.core.validators
import django.db.models.deletion
import driver_applications.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_entry_date', models.DateField()),
                ('requested_entry_time', models.TimeField()),
                ('estimated_duration', models.PositiveIntegerField(help_text='Estimated stay duration in minutes')),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?91?[6-9]\\d{9}$', 'Enter a valid Indian phone number')])),
                ('driver_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('driver_license_number', models.CharField(max_length=20, unique=True)),
                ('driver_photo', models.ImageField(upload_to=driver_applications.models.upload_driver_photo)),
                ('vehicle_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[A-Z]{2}[0-9]{1,2}[A-Z]{0,2}[0-9]{1,4}$', 'Enter valid vehicle number')])),
                ('vehicle_type', models.CharField(default='large', max_length=50)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_capacity', models.CharField(help_text='e.g., 10 tons, 50 passengers', max_length=50)),
                ('source_company_name', models.CharField(max_length=200)),
                ('source_company_address', models.TextField()),
                ('source_company_contact', models.CharField(max_length=15)),
                ('destination_within_premises', models.CharField(help_text='Specific location within Forbes Marshall', max_length=200)),
                ('material_type', models.CharField(choices=[('raw_materials', 'Raw Materials'), ('finished_goods', 'Finished Products'), ('office_supplies', 'Office Supplies'), ('equipment', 'Equipment/Machinery'), ('maintenance', 'Maintenance Supplies'), ('waste_disposal', 'Waste/Disposal'), ('food_beverages', 'Food & Beverages'), ('documents', 'Documents/Papers'), ('other', 'Other (Specify)')], max_length=20)),
                ('material_description', models.TextField(help_text='Detailed description of materials/purpose')),
                ('material_weight', models.CharField(blank=True, help_text='Approximate weight', max_length=50)),
                ('material_value', models.DecimalField(blank=True, decimal_places=2, help_text='Approximate value in INR', max_digits=12, null=True)),
                ('urgency', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('emergency', 'Emergency')], default='medium', max_length=10)),
                ('vehicle_rc', models.FileField(help_text='Vehicle Registration Certificate', upload_to=driver_applications.models.upload_vehicle_rc)),
                ('vehicle_insurance', models.FileField(help_text='Valid Vehicle Insurance', upload_to=driver_applications.models.upload_insurance)),
                ('puc_certificate', models.FileField(help_text='Pollution Under Control Certificate', upload_to=driver_applications.models.upload_puc)),
                ('material_receipt', models.FileField(help_text='Material receipt/invoice from source', upload_to=driver_applications.models.upload_material_receipt)),
                ('goods_transport_permit', models.FileField(blank=True, null=True, upload_to='driver_applications/permits/')),
                ('customs_clearance', models.FileField(blank=True, null=True, upload_to='driver_applications/customs/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=15)),
                ('reviewed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_comments', models.TextField(blank=True, help_text='Internal comments from security/admin')),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_entry_slot', models.CharField(blank=True, max_length=10, null=True)),
                ('actual_entry_time', models.DateTimeField(blank=True, null=True)),
                ('actual_exit_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Driver Application',
                'verbose_name_plural': 'Driver Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=15)),
                ('new_status', models.CharField(max_length=15)),
                ('changed_by', models.CharField(max_length=100)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='driver_applications.driverapplication')),
            ],
            options={
                'verbose_name': 'Status History',
                'verbose_name_plural': 'Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_by', models.CharField(max_length=100)),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_internal', models.BooleanField(default=True, help_text='Internal comment (not visible to driver)')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='driver_applications.driverapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
