# Generated by Django 5.1.1 on 2025-11-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverapplication',
            name='driver_license_number',
            field=models.CharField(max_length=20),
        ),
    ]
