# Generated by Django 5.1.1 on 2025-11-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_applications', '0002_alter_driverapplication_driver_license_number'),
    ]

    operations = [
                # Use RUNSQL blocks that ignore "column already exists" errors on Oracle (ORA-01430)
                migrations.RunSQL(
                        sql="""
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE DRIVER_APPLICATIONS_DRIVERAPPLICATION ADD (customs_clearance_blob BLOB)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
""",
                        reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                        sql="""
BEGIN
    EXECUTE IMMEDIATE "ALTER TABLE DRIVER_APPLICATIONS_DRIVERAPPLICATION ADD (customs_clearance_name VARCHAR2(255))";
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
""",
                        reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                        sql="""
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE DRIVER_APPLICATIONS_DRIVERAPPLICATION ADD (driver_photo_blob BLOB)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
""",
                        reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                        sql="""
BEGIN
    EXECUTE IMMEDIATE "ALTER TABLE DRIVER_APPLICATIONS_DRIVERAPPLICATION ADD (driver_photo_name VARCHAR2(255))";
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
""",
                        reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                        sql="""
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE DRIVER_APPLICATIONS_DRIVERAPPLICATION ADD (goods_transport_permit_blob BLOB)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
""",
                        reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                        sql="""
BEGIN
    EXECUTE IMMEDIATE "ALTER TABLE DRIVER_APPLICATIONS_DRIVERAPPLICATION ADD (goods_transport_permit_name VARCHAR2(255))";
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
""",
                        reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                        sql="""
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE DRIVER_APPLICATIONS_DRIVERAPPLICATION ADD (material_receipt_blob BLOB)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
""",
                        reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                        sql="""
BEGIN
    EXECUTE IMMEDIATE "ALTER TABLE DRIVER_APPLICATIONS_DRIVERAPPLICATION ADD (material_receipt_name VARCHAR2(255))";
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
""",
                        reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                        sql="""
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE DRIVER_APPLICATIONS_DRIVERAPPLICATION ADD (puc_certificate_blob BLOB)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
""",
                        reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                        sql="""
BEGIN
    EXECUTE IMMEDIATE "ALTER TABLE DRIVER_APPLICATIONS_DRIVERAPPLICATION ADD (puc_certificate_name VARCHAR2(255))";
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
""",
                        reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                        sql="""
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE DRIVER_APPLICATIONS_DRIVERAPPLICATION ADD (vehicle_insurance_blob BLOB)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
""",
                        reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                        sql="""
BEGIN
    EXECUTE IMMEDIATE "ALTER TABLE DRIVER_APPLICATIONS_DRIVERAPPLICATION ADD (vehicle_insurance_name VARCHAR2(255))";
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
""",
                        reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                        sql="""
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE DRIVER_APPLICATIONS_DRIVERAPPLICATION ADD (vehicle_rc_blob BLOB)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
""",
                        reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                        sql="""
BEGIN
    EXECUTE IMMEDIATE "ALTER TABLE DRIVER_APPLICATIONS_DRIVERAPPLICATION ADD (vehicle_rc_name VARCHAR2(255))";
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
""",
                        reverse_sql=migrations.RunSQL.noop,
                ),
    ]
