# Generated by Django 5.1.1 on 2025-11-30 14:27

from django.db import migrations


class Migration(migrations.Migration):

    # This is an empty/no-op migration kept for historical compatibility.
    # The actual column additions are handled in 0003 using DB-safe RunSQL blocks.
    dependencies = [
        ('driver_applications', '0003_driverapplication_customs_clearance_blob_and_more'),
    ]

    operations = [
        migrations.RunSQL(migrations.RunSQL.noop, migrations.RunSQL.noop),
    ]
