# Generated by Django 5.1.1 on 2025-12-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_applications', '0004_driverapplication_customs_clearance_blob_and_more'),
    ]

    operations = [
        # Only add the new driver license photo fields using Oracle-safe AddField
        migrations.AddField(
            model_name='driverapplication',
            name='driver_license_photo_blob',
            field=models.BinaryField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='driverapplication',
            name='driver_license_photo_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
