-- ============================================================================
-- Forbes Marshall Parking Management System - Database Initialization Script
-- Oracle Database 19c
-- ============================================================================
-- This script creates all necessary tables and relationships for the parking
-- management system including parking slots, vehicles, sessions, and driver
-- applications.
-- ============================================================================

-- Connect as system user
-- Run this script with: sqlplus system/system123@localhost:1521/orclpdb @init_database.sql

SET SERVEROUTPUT ON;
SET ECHO ON;

PROMPT ============================================================================
PROMPT Starting Forbes Marshall Parking Management System Database Setup
PROMPT ============================================================================

-- ============================================================================
-- CLEANUP: Drop existing tables if they exist (for fresh installation)
-- ============================================================================
PROMPT
PROMPT Cleaning up existing tables (if any)...
PROMPT

BEGIN
    -- Drop driver application related tables
    EXECUTE IMMEDIATE 'DROP TABLE DRIVER_APPLICATIONS_APPLICATIONSTATUSHISTORY CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('Dropped DRIVER_APPLICATIONS_APPLICATIONSTATUSHISTORY');
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DRIVER_APPLICATIONS_APPLICATIONCOMMENT CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('Dropped DRIVER_APPLICATIONS_APPLICATIONCOMMENT');
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DRIVER_APPLICATIONS_DRIVERAPPLICATION CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('Dropped DRIVER_APPLICATIONS_DRIVERAPPLICATION');
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    -- Drop parking related tables
    EXECUTE IMMEDIATE 'DROP TABLE PARKING_APP_PARKINGSESSION CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('Dropped PARKING_APP_PARKINGSESSION');
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PARKING_APP_LARGEVEHICLEREQUEST CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('Dropped PARKING_APP_LARGEVEHICLEREQUEST');
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PARKING_APP_VEHICLE CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('Dropped PARKING_APP_VEHICLE');
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PARKING_APP_PARKINGSLOT CASCADE CONSTRAINTS';
    DBMS_OUTPUT.PUT_LINE('Dropped PARKING_APP_PARKINGSLOT');
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    -- Drop sequences
    EXECUTE IMMEDIATE 'DROP SEQUENCE PARKING_APP_VEHICLE_SEQ';
    DBMS_OUTPUT.PUT_LINE('Dropped PARKING_APP_VEHICLE_SEQ');
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE PARKING_APP_PARKINGSLOT_SEQ';
    DBMS_OUTPUT.PUT_LINE('Dropped PARKING_APP_PARKINGSLOT_SEQ');
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE PARKING_APP_PARKINGSESSION_SEQ';
    DBMS_OUTPUT.PUT_LINE('Dropped PARKING_APP_PARKINGSESSION_SEQ');
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE PARKING_APP_LARGEVEHICLEREQUEST_SEQ';
    DBMS_OUTPUT.PUT_LINE('Dropped PARKING_APP_LARGEVEHICLEREQUEST_SEQ');
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE DRIVER_APPLICATIONS_DRIVERAPPLICATION_SEQ';
    DBMS_OUTPUT.PUT_LINE('Dropped DRIVER_APPLICATIONS_DRIVERAPPLICATION_SEQ');
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE DRIVER_APPLICATIONS_APPLICATIONCOMMENT_SEQ';
    DBMS_OUTPUT.PUT_LINE('Dropped DRIVER_APPLICATIONS_APPLICATIONCOMMENT_SEQ');
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE DRIVER_APPLICATIONS_APPLICATIONSTATUSHISTORY_SEQ';
    DBMS_OUTPUT.PUT_LINE('Dropped DRIVER_APPLICATIONS_APPLICATIONSTATUSHISTORY_SEQ');
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

COMMIT;

-- ============================================================================
-- CREATE SEQUENCES for Auto-Increment IDs
-- ============================================================================
PROMPT
PROMPT Creating sequences for auto-increment IDs...
PROMPT

CREATE SEQUENCE PARKING_APP_VEHICLE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE PARKING_APP_PARKINGSLOT_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE PARKING_APP_PARKINGSESSION_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE PARKING_APP_LARGEVEHICLEREQUEST_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE DRIVER_APPLICATIONS_DRIVERAPPLICATION_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE DRIVER_APPLICATIONS_APPLICATIONCOMMENT_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE DRIVER_APPLICATIONS_APPLICATIONSTATUSHISTORY_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

PROMPT Sequences created successfully!

-- ============================================================================
-- TABLE 1: PARKING_APP_VEHICLE
-- Stores registered vehicle information
-- ============================================================================
PROMPT
PROMPT Creating PARKING_APP_VEHICLE table...
PROMPT

CREATE TABLE PARKING_APP_VEHICLE (
    ID NUMBER(11) NOT NULL,
    LICENSE_PLATE VARCHAR2(20) NOT NULL,
    OWNER_CONTACT VARCHAR2(15),
    VEHICLE_TYPE VARCHAR2(20) NOT NULL,
    REGISTERED_STATE VARCHAR2(2),
    CONTACT_NUMBER VARCHAR2(15),
    CREATED_AT TIMESTAMP(6) NOT NULL,
    OWNER_NAME VARCHAR2(100),
    
    -- Constraints
    CONSTRAINT PK_VEHICLE PRIMARY KEY (ID),
    CONSTRAINT UQ_VEHICLE_LICENSE UNIQUE (LICENSE_PLATE),
    CONSTRAINT CHK_VEHICLE_TYPE CHECK (VEHICLE_TYPE IN ('two_wheeler', 'sedan', 'suv', 'large')),
    CONSTRAINT CHK_REGISTERED_STATE CHECK (REGISTERED_STATE IN (
        'AN', 'AP', 'AR', 'AS', 'BR', 'CH', 'CG', 'DH', 'DD', 'DL',
        'GA', 'GJ', 'HR', 'HP', 'JK', 'JH', 'KA', 'KL', 'LD', 'MP',
        'MH', 'MN', 'ML', 'MZ', 'NL', 'OR', 'PY', 'PB', 'RJ', 'SK',
        'TN', 'TS', 'TR', 'UP', 'UK', 'WB'
    ))
);

-- Create index for faster lookups
CREATE INDEX IDX_VEHICLE_LICENSE ON PARKING_APP_VEHICLE(LICENSE_PLATE);
CREATE INDEX IDX_VEHICLE_TYPE ON PARKING_APP_VEHICLE(VEHICLE_TYPE);

PROMPT PARKING_APP_VEHICLE table created successfully!

-- ============================================================================
-- TABLE 2: PARKING_APP_PARKINGSLOT
-- Stores parking slot inventory and status
-- ============================================================================
PROMPT
PROMPT Creating PARKING_APP_PARKINGSLOT table...
PROMPT

CREATE TABLE PARKING_APP_PARKINGSLOT (
    ID NUMBER(11) NOT NULL,
    SLOT_NUMBER VARCHAR2(10) NOT NULL,
    SLOT_TYPE VARCHAR2(20) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'available' NOT NULL,
    IS_OCCUPIED NUMBER(1) DEFAULT 0 NOT NULL,
    LAST_UPDATED TIMESTAMP(6) NOT NULL,
    FLOOR_LEVEL NUMBER(11) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    
    -- Constraints
    CONSTRAINT PK_PARKINGSLOT PRIMARY KEY (ID),
    CONSTRAINT UQ_SLOT_NUMBER UNIQUE (SLOT_NUMBER),
    CONSTRAINT CHK_SLOT_TYPE CHECK (SLOT_TYPE IN ('two_wheeler', 'car', 'large', 'disabled', 'vip')),
    CONSTRAINT CHK_SLOT_STATUS CHECK (STATUS IN ('available', 'occupied', 'maintenance', 'out_of_service')),
    CONSTRAINT CHK_IS_OCCUPIED CHECK (IS_OCCUPIED IN (0, 1))
);

-- Create indexes for faster queries
CREATE INDEX IDX_SLOT_TYPE ON PARKING_APP_PARKINGSLOT(SLOT_TYPE);
CREATE INDEX IDX_SLOT_STATUS ON PARKING_APP_PARKINGSLOT(STATUS);
CREATE INDEX IDX_SLOT_AVAILABLE ON PARKING_APP_PARKINGSLOT(STATUS, SLOT_TYPE);

PROMPT PARKING_APP_PARKINGSLOT table created successfully!

-- ============================================================================
-- TABLE 3: PARKING_APP_PARKINGSESSION
-- Stores parking session records (entry/exit tracking)
-- ============================================================================
PROMPT
PROMPT Creating PARKING_APP_PARKINGSESSION table...
PROMPT

CREATE TABLE PARKING_APP_PARKINGSESSION (
    ID NUMBER(11) NOT NULL,
    VEHICLE_ID NUMBER(11) NOT NULL,
    PARKING_SLOT_ID NUMBER(11) NOT NULL,
    ENTRY_TIME TIMESTAMP(6) NOT NULL,
    EXIT_TIME TIMESTAMP(6),
    STATUS VARCHAR2(10) DEFAULT 'Active' NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    
    -- Constraints
    CONSTRAINT PK_PARKINGSESSION PRIMARY KEY (ID),
    CONSTRAINT FK_SESSION_VEHICLE FOREIGN KEY (VEHICLE_ID) 
        REFERENCES PARKING_APP_VEHICLE(ID) ON DELETE CASCADE,
    CONSTRAINT FK_SESSION_SLOT FOREIGN KEY (PARKING_SLOT_ID) 
        REFERENCES PARKING_APP_PARKINGSLOT(ID) ON DELETE CASCADE,
    CONSTRAINT CHK_SESSION_STATUS CHECK (STATUS IN ('Active', 'Completed')),
    CONSTRAINT CHK_SESSION_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
);

-- Create indexes for faster queries
CREATE INDEX IDX_SESSION_VEHICLE ON PARKING_APP_PARKINGSESSION(VEHICLE_ID);
CREATE INDEX IDX_SESSION_SLOT ON PARKING_APP_PARKINGSESSION(PARKING_SLOT_ID);
CREATE INDEX IDX_SESSION_STATUS ON PARKING_APP_PARKINGSESSION(STATUS);
CREATE INDEX IDX_SESSION_ACTIVE ON PARKING_APP_PARKINGSESSION(IS_ACTIVE);
CREATE INDEX IDX_SESSION_ENTRY ON PARKING_APP_PARKINGSESSION(ENTRY_TIME);

-- Unique constraint: Only one active session per slot
CREATE UNIQUE INDEX UQ_ACTIVE_SESSION_PER_SLOT 
    ON PARKING_APP_PARKINGSESSION(PARKING_SLOT_ID) 
    WHERE IS_ACTIVE = 1;

PROMPT PARKING_APP_PARKINGSESSION table created successfully!

-- ============================================================================
-- TABLE 4: PARKING_APP_LARGEVEHICLEREQUEST
-- Stores quick large vehicle entry requests
-- ============================================================================
PROMPT
PROMPT Creating PARKING_APP_LARGEVEHICLEREQUEST table...
PROMPT

CREATE TABLE PARKING_APP_LARGEVEHICLEREQUEST (
    ID NUMBER(11) NOT NULL,
    LICENSE_PLATE VARCHAR2(20) NOT NULL,
    OWNER_NAME VARCHAR2(100),
    CONTACT_NUMBER VARCHAR2(15) NOT NULL,
    REGISTERED_STATE VARCHAR2(2),
    REQUESTED_AT TIMESTAMP(6) NOT NULL,
    STATUS VARCHAR2(10) DEFAULT 'pending' NOT NULL,
    NOTES CLOB,
    
    -- Constraints
    CONSTRAINT PK_LARGEVEHICLEREQUEST PRIMARY KEY (ID),
    CONSTRAINT CHK_LVR_STATUS CHECK (STATUS IN ('pending', 'approved', 'rejected')),
    CONSTRAINT CHK_LVR_STATE CHECK (REGISTERED_STATE IN (
        'AN', 'AP', 'AR', 'AS', 'BR', 'CH', 'CG', 'DH', 'DD', 'DL',
        'GA', 'GJ', 'HR', 'HP', 'JK', 'JH', 'KA', 'KL', 'LD', 'MP',
        'MH', 'MN', 'ML', 'MZ', 'NL', 'OR', 'PY', 'PB', 'RJ', 'SK',
        'TN', 'TS', 'TR', 'UP', 'UK', 'WB'
    ))
);

-- Create indexes
CREATE INDEX IDX_LVR_STATUS ON PARKING_APP_LARGEVEHICLEREQUEST(STATUS);
CREATE INDEX IDX_LVR_REQUESTED ON PARKING_APP_LARGEVEHICLEREQUEST(REQUESTED_AT);

PROMPT PARKING_APP_LARGEVEHICLEREQUEST table created successfully!

-- ============================================================================
-- TABLE 5: DRIVER_APPLICATIONS_DRIVERAPPLICATION
-- Stores comprehensive driver entry applications for large vehicles
-- ============================================================================
PROMPT
PROMPT Creating DRIVER_APPLICATIONS_DRIVERAPPLICATION table...
PROMPT

CREATE TABLE DRIVER_APPLICATIONS_DRIVERAPPLICATION (
    ID NUMBER(11) NOT NULL,
    APPLICATION_ID RAW(16) NOT NULL,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    UPDATED_AT TIMESTAMP(6) NOT NULL,
    REQUESTED_ENTRY_DATE DATE NOT NULL,
    REQUESTED_ENTRY_TIME TIMESTAMP(6) NOT NULL,
    ESTIMATED_DURATION NUMBER(10) NOT NULL,
    
    -- Driver Information
    DRIVER_NAME VARCHAR2(100) NOT NULL,
    DRIVER_PHONE VARCHAR2(15) NOT NULL,
    DRIVER_EMAIL VARCHAR2(254),
    DRIVER_LICENSE_NUMBER VARCHAR2(20) NOT NULL,
    
    -- Vehicle Information
    VEHICLE_NUMBER VARCHAR2(15) NOT NULL,
    VEHICLE_TYPE VARCHAR2(50) DEFAULT 'large' NOT NULL,
    VEHICLE_MODEL VARCHAR2(100) NOT NULL,
    VEHICLE_CAPACITY VARCHAR2(50) NOT NULL,
    
    -- Company/Business Information
    SOURCE_COMPANY_NAME VARCHAR2(200) NOT NULL,
    SOURCE_COMPANY_ADDRESS CLOB NOT NULL,
    SOURCE_COMPANY_CONTACT VARCHAR2(15) NOT NULL,
    DESTINATION_WITHIN_PREMISES VARCHAR2(200) NOT NULL,
    
    -- Material/Purpose Information
    MATERIAL_TYPE VARCHAR2(20) NOT NULL,
    MATERIAL_DESCRIPTION CLOB NOT NULL,
    MATERIAL_WEIGHT VARCHAR2(50),
    MATERIAL_VALUE NUMBER(12, 2),
    URGENCY VARCHAR2(10) DEFAULT 'medium' NOT NULL,
    
    -- Document Storage (BLOB fields for binary data)
    DRIVER_PHOTO_BLOB BLOB,
    DRIVER_PHOTO_NAME VARCHAR2(255),
    DRIVER_LICENSE_PHOTO_BLOB BLOB,
    DRIVER_LICENSE_PHOTO_NAME VARCHAR2(255),
    VEHICLE_RC_BLOB BLOB,
    VEHICLE_RC_NAME VARCHAR2(255),
    VEHICLE_INSURANCE_BLOB BLOB,
    VEHICLE_INSURANCE_NAME VARCHAR2(255),
    PUC_CERTIFICATE_BLOB BLOB,
    PUC_CERTIFICATE_NAME VARCHAR2(255),
    MATERIAL_RECEIPT_BLOB BLOB,
    MATERIAL_RECEIPT_NAME VARCHAR2(255),
    GOODS_TRANSPORT_PERMIT_BLOB BLOB,
    GOODS_TRANSPORT_PERMIT_NAME VARCHAR2(255),
    CUSTOMS_CLEARANCE_BLOB BLOB,
    CUSTOMS_CLEARANCE_NAME VARCHAR2(255),
    
    -- Application Status
    STATUS VARCHAR2(15) DEFAULT 'pending' NOT NULL,
    REVIEWED_BY VARCHAR2(100),
    REVIEWED_AT TIMESTAMP(6),
    ADMIN_COMMENTS CLOB,
    REJECTION_REASON CLOB,
    
    -- Entry Details (filled after approval)
    APPROVED_ENTRY_SLOT VARCHAR2(10),
    ACTUAL_ENTRY_TIME TIMESTAMP(6),
    ACTUAL_EXIT_TIME TIMESTAMP(6),
    
    -- Constraints
    CONSTRAINT PK_DRIVERAPPLICATION PRIMARY KEY (ID),
    CONSTRAINT UQ_APPLICATION_ID UNIQUE (APPLICATION_ID),
    CONSTRAINT CHK_APP_STATUS CHECK (STATUS IN ('pending', 'under_review', 'approved', 'rejected', 'expired')),
    CONSTRAINT CHK_APP_MATERIAL_TYPE CHECK (MATERIAL_TYPE IN (
        'raw_materials', 'finished_goods', 'office_supplies', 'equipment',
        'maintenance', 'waste_disposal', 'food_beverages', 'documents', 'other'
    )),
    CONSTRAINT CHK_APP_URGENCY CHECK (URGENCY IN ('low', 'medium', 'high', 'emergency'))
);

-- Create indexes for faster queries
CREATE INDEX IDX_APP_STATUS ON DRIVER_APPLICATIONS_DRIVERAPPLICATION(STATUS);
CREATE INDEX IDX_APP_CREATED ON DRIVER_APPLICATIONS_DRIVERAPPLICATION(CREATED_AT);
CREATE INDEX IDX_APP_ENTRY_DATE ON DRIVER_APPLICATIONS_DRIVERAPPLICATION(REQUESTED_ENTRY_DATE);
CREATE INDEX IDX_APP_VEHICLE_NUM ON DRIVER_APPLICATIONS_DRIVERAPPLICATION(VEHICLE_NUMBER);
CREATE INDEX IDX_APP_DRIVER_NAME ON DRIVER_APPLICATIONS_DRIVERAPPLICATION(DRIVER_NAME);

PROMPT DRIVER_APPLICATIONS_DRIVERAPPLICATION table created successfully!

-- ============================================================================
-- TABLE 6: DRIVER_APPLICATIONS_APPLICATIONCOMMENT
-- Stores comments/notes on driver applications
-- ============================================================================
PROMPT
PROMPT Creating DRIVER_APPLICATIONS_APPLICATIONCOMMENT table...
PROMPT

CREATE TABLE DRIVER_APPLICATIONS_APPLICATIONCOMMENT (
    ID NUMBER(11) NOT NULL,
    APPLICATION_ID NUMBER(11) NOT NULL,
    COMMENT_BY VARCHAR2(100) NOT NULL,
    COMMENT_TEXT CLOB NOT NULL,
    CREATED_AT TIMESTAMP(6) NOT NULL,
    IS_INTERNAL NUMBER(1) DEFAULT 1 NOT NULL,
    
    -- Constraints
    CONSTRAINT PK_APPLICATIONCOMMENT PRIMARY KEY (ID),
    CONSTRAINT FK_COMMENT_APPLICATION FOREIGN KEY (APPLICATION_ID) 
        REFERENCES DRIVER_APPLICATIONS_DRIVERAPPLICATION(ID) ON DELETE CASCADE,
    CONSTRAINT CHK_COMMENT_INTERNAL CHECK (IS_INTERNAL IN (0, 1))
);

-- Create indexes
CREATE INDEX IDX_COMMENT_APP ON DRIVER_APPLICATIONS_APPLICATIONCOMMENT(APPLICATION_ID);
CREATE INDEX IDX_COMMENT_CREATED ON DRIVER_APPLICATIONS_APPLICATIONCOMMENT(CREATED_AT);

PROMPT DRIVER_APPLICATIONS_APPLICATIONCOMMENT table created successfully!

-- ============================================================================
-- TABLE 7: DRIVER_APPLICATIONS_APPLICATIONSTATUSHISTORY
-- Tracks all status changes for audit trail
-- ============================================================================
PROMPT
PROMPT Creating DRIVER_APPLICATIONS_APPLICATIONSTATUSHISTORY table...
PROMPT

CREATE TABLE DRIVER_APPLICATIONS_APPLICATIONSTATUSHISTORY (
    ID NUMBER(11) NOT NULL,
    APPLICATION_ID NUMBER(11) NOT NULL,
    PREVIOUS_STATUS VARCHAR2(15) NOT NULL,
    NEW_STATUS VARCHAR2(15) NOT NULL,
    CHANGED_BY VARCHAR2(100) NOT NULL,
    CHANGED_AT TIMESTAMP(6) NOT NULL,
    REASON CLOB,
    
    -- Constraints
    CONSTRAINT PK_STATUSHISTORY PRIMARY KEY (ID),
    CONSTRAINT FK_HISTORY_APPLICATION FOREIGN KEY (APPLICATION_ID) 
        REFERENCES DRIVER_APPLICATIONS_DRIVERAPPLICATION(ID) ON DELETE CASCADE
);

-- Create indexes
CREATE INDEX IDX_HISTORY_APP ON DRIVER_APPLICATIONS_APPLICATIONSTATUSHISTORY(APPLICATION_ID);
CREATE INDEX IDX_HISTORY_CHANGED ON DRIVER_APPLICATIONS_APPLICATIONSTATUSHISTORY(CHANGED_AT);

PROMPT DRIVER_APPLICATIONS_APPLICATIONSTATUSHISTORY table created successfully!

-- ============================================================================
-- CREATE TRIGGERS for Auto-Increment using Sequences
-- ============================================================================
PROMPT
PROMPT Creating triggers for auto-increment IDs...
PROMPT

-- Trigger for PARKING_APP_VEHICLE
CREATE OR REPLACE TRIGGER TRG_VEHICLE_ID
BEFORE INSERT ON PARKING_APP_VEHICLE
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT PARKING_APP_VEHICLE_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- Trigger for PARKING_APP_PARKINGSLOT
CREATE OR REPLACE TRIGGER TRG_PARKINGSLOT_ID
BEFORE INSERT ON PARKING_APP_PARKINGSLOT
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT PARKING_APP_PARKINGSLOT_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- Trigger for PARKING_APP_PARKINGSESSION
CREATE OR REPLACE TRIGGER TRG_PARKINGSESSION_ID
BEFORE INSERT ON PARKING_APP_PARKINGSESSION
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT PARKING_APP_PARKINGSESSION_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- Trigger for PARKING_APP_LARGEVEHICLEREQUEST
CREATE OR REPLACE TRIGGER TRG_LARGEVEHICLEREQUEST_ID
BEFORE INSERT ON PARKING_APP_LARGEVEHICLEREQUEST
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT PARKING_APP_LARGEVEHICLEREQUEST_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- Trigger for DRIVER_APPLICATIONS_DRIVERAPPLICATION
CREATE OR REPLACE TRIGGER TRG_DRIVERAPPLICATION_ID
BEFORE INSERT ON DRIVER_APPLICATIONS_DRIVERAPPLICATION
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT DRIVER_APPLICATIONS_DRIVERAPPLICATION_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- Trigger for DRIVER_APPLICATIONS_APPLICATIONCOMMENT
CREATE OR REPLACE TRIGGER TRG_APPLICATIONCOMMENT_ID
BEFORE INSERT ON DRIVER_APPLICATIONS_APPLICATIONCOMMENT
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT DRIVER_APPLICATIONS_APPLICATIONCOMMENT_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

-- Trigger for DRIVER_APPLICATIONS_APPLICATIONSTATUSHISTORY
CREATE OR REPLACE TRIGGER TRG_STATUSHISTORY_ID
BEFORE INSERT ON DRIVER_APPLICATIONS_APPLICATIONSTATUSHISTORY
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT DRIVER_APPLICATIONS_APPLICATIONSTATUSHISTORY_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

PROMPT Triggers created successfully!

-- ============================================================================
-- INSERT SAMPLE DATA: Parking Slots
-- ============================================================================
PROMPT
PROMPT Inserting parking slots...
PROMPT

-- Two-Wheeler Slots (T001-T050)
BEGIN
    FOR i IN 1..50 LOOP
        INSERT INTO PARKING_APP_PARKINGSLOT (
            SLOT_NUMBER, SLOT_TYPE, STATUS, IS_OCCUPIED, 
            LAST_UPDATED, FLOOR_LEVEL, CREATED_AT
        ) VALUES (
            'T' || LPAD(i, 3, '0'), 
            'two_wheeler', 
            'available', 
            0, 
            SYSTIMESTAMP, 
            1, 
            SYSTIMESTAMP
        );
    END LOOP;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Inserted 50 two-wheeler slots (T001-T050)');
END;
/

-- Car Slots (C001-C030)
BEGIN
    FOR i IN 1..30 LOOP
        INSERT INTO PARKING_APP_PARKINGSLOT (
            SLOT_NUMBER, SLOT_TYPE, STATUS, IS_OCCUPIED, 
            LAST_UPDATED, FLOOR_LEVEL, CREATED_AT
        ) VALUES (
            'C' || LPAD(i, 3, '0'), 
            'car', 
            'available', 
            0, 
            SYSTIMESTAMP, 
            1, 
            SYSTIMESTAMP
        );
    END LOOP;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Inserted 30 car slots (C001-C030)');
END;
/

-- Large Vehicle Slots (L001-L020)
BEGIN
    FOR i IN 1..20 LOOP
        INSERT INTO PARKING_APP_PARKINGSLOT (
            SLOT_NUMBER, SLOT_TYPE, STATUS, IS_OCCUPIED, 
            LAST_UPDATED, FLOOR_LEVEL, CREATED_AT
        ) VALUES (
            'L' || LPAD(i, 3, '0'), 
            'large', 
            'available', 
            0, 
            SYSTIMESTAMP, 
            1, 
            SYSTIMESTAMP
        );
    END LOOP;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Inserted 20 large vehicle slots (L001-L020)');
END;
/

-- ============================================================================
-- VERIFICATION: Display table counts
-- ============================================================================
PROMPT
PROMPT ============================================================================
PROMPT Database Setup Complete!
PROMPT ============================================================================
PROMPT
PROMPT Verifying table creation and data insertion...
PROMPT

SET LINESIZE 200
COLUMN TABLE_NAME FORMAT A40
COLUMN ROW_COUNT FORMAT 999,999

SELECT 'PARKING_APP_VEHICLE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM PARKING_APP_VEHICLE
UNION ALL
SELECT 'PARKING_APP_PARKINGSLOT', COUNT(*) FROM PARKING_APP_PARKINGSLOT
UNION ALL
SELECT 'PARKING_APP_PARKINGSESSION', COUNT(*) FROM PARKING_APP_PARKINGSESSION
UNION ALL
SELECT 'PARKING_APP_LARGEVEHICLEREQUEST', COUNT(*) FROM PARKING_APP_LARGEVEHICLEREQUEST
UNION ALL
SELECT 'DRIVER_APPLICATIONS_DRIVERAPPLICATION', COUNT(*) FROM DRIVER_APPLICATIONS_DRIVERAPPLICATION
UNION ALL
SELECT 'DRIVER_APPLICATIONS_APPLICATIONCOMMENT', COUNT(*) FROM DRIVER_APPLICATIONS_APPLICATIONCOMMENT
UNION ALL
SELECT 'DRIVER_APPLICATIONS_APPLICATIONSTATUSHISTORY', COUNT(*) FROM DRIVER_APPLICATIONS_APPLICATIONSTATUSHISTORY;

PROMPT
PROMPT Slot Distribution:
PROMPT

SELECT 
    SLOT_TYPE,
    COUNT(*) AS TOTAL_SLOTS,
    SUM(CASE WHEN STATUS = 'available' THEN 1 ELSE 0 END) AS AVAILABLE,
    SUM(CASE WHEN STATUS = 'occupied' THEN 1 ELSE 0 END) AS OCCUPIED,
    SUM(CASE WHEN STATUS = 'maintenance' THEN 1 ELSE 0 END) AS MAINTENANCE
FROM PARKING_APP_PARKINGSLOT
GROUP BY SLOT_TYPE
ORDER BY SLOT_TYPE;

PROMPT
PROMPT ============================================================================
PROMPT Setup Summary:
PROMPT ============================================================================
PROMPT - Created 7 main tables with proper relationships
PROMPT - Created 7 sequences for auto-increment IDs
PROMPT - Created 7 triggers for automatic ID generation
PROMPT - Created indexes for optimized queries
PROMPT - Inserted 100 parking slots (50 two-wheeler, 30 car, 20 large)
PROMPT
PROMPT Next Steps:
PROMPT 1. Run Django migrations: python manage.py migrate --fake-initial
PROMPT 2. Create superuser: python manage.py createsuperuser
PROMPT 3. Set staff status: UPDATE AUTH_USER SET IS_STAFF = 1 WHERE USERNAME = 'admin';
PROMPT 4. Start server: python manage.py runserver
PROMPT
PROMPT ============================================================================
PROMPT Forbes Marshall Parking Management System is ready to use!
PROMPT ============================================================================

COMMIT;
EXIT;
